site_name: prdeploy
docs_dir: docs
repo_url: https://github.com/greggbjensen/prdeploy
edit_uri: blob/main/docs/
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true
nav:
  - Introduction: 'index.md'
  - 'Getting started':
      - 'Overview': 'getting-started/overview.md'
      - '1. GitHub App': 'getting-started/1-github-app.md'
      - '2. GitHub OAuth App': 'getting-started/2-github-oauth-app.md'
      - '3. Slack App': 'getting-started/3-slack-app.md'
      - '4. Repo Config': 'getting-started/4-repo-config.md'
      - '5. GitHub Actions': 'getting-started/5-github-actions.md'
  - 'Comment Commands': 'comment-commands.md'
  - 'Slack Notifications': 'slack-notifications.md'
  - 'prdeploy portal': 'prdeploy-portal.md'
  - 'Issue Tracker': 'https://github.com/greggbjensen/prdeploy/issues'