site_name: prdeploy
docs_dir: docs
repo_url: https://github.com/greggbjensen/prdeploy
edit_uri: blob/main/docs/
theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/favicon.png
markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Introduction: 'index.md'
  - 'Getting started':
      - 'Overview': 'getting-started/overview.md'
      - '1. GitHub App': 'getting-started/1-github-app.md'
      - '2. GitHub OAuth App': 'getting-started/2-github-oauth-app.md'
      - '3. Slack App': 'getting-started/3-slack-app.md'
      - '4. Jira integration': 'getting-started/4-jira-integration.md'
      - '5. AWS configuration': 'getting-started/5-aws-configuration.md'
      - '6. prdeploy portal': 'getting-started/6-prdeploy-portal.md'
      - '7. GitHub Actions': 'getting-started/7-github-actions.md'
  - 'Comment commands': 'comment-commands.md'
  - 'prdeploy portal': 'prdeploy-portal.md'
  - 'Slack notifications': 'slack-notifications.md'
  - 'JIRA links': 'jira-links.md'
  - 'Deployment queues': 'deployment-queues.md'
  - 'Issue tracker': 'https://github.com/greggbjensen/prdeploy/issues'