site_name: prdeploy
docs_dir: docs
repo_url: https://github.com/greggbjensen/prdeploy
edit_uri: blob/main/docs/
theme:
  name: material
nav:
  - Introduction: 'index.md'
  - 'Issue Tracker': 'https://github.com/greggbjensen/prdeploy/issues'