{{- $pathPrefix := .Values.global.aws.secretPathPrefix -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "prdeploy-webhooks.fullname" . }}-external
  labels:
    {{- include "prdeploy-webhooks.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "prdeploy.fullname" . }}
    kind: SecretStore
  target:
    name: {{ include "prdeploy-webhooks.fullname" . }}-external
    creationPolicy: Owner
  data:
    {{- range $key, $val := .Values.externalSecrets }}
    - secretKey: {{ $key }}
      remoteRef:
        key: "{{ $pathPrefix }}/{{ $val }}"
    {{- end -}}