<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Amazon.AspNetCore.DataProtection.SSM" Version="4.0.1" />
    <PackageVersion Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.3.14" />
    <PackageVersion Include="AWSSDK.SecurityToken" Version="4.0.5.1" />
    <PackageVersion Include="AWSSDK.SimpleSystemsManagement" Version="4.0.6.4" />
    <PackageVersion Include="AWSSDK.SSO" Version="4.0.2.5" />
    <PackageVersion Include="AWSSDK.SSOOIDC" Version="4.0.3.6" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="FluentValidation" Version="12.1.0" />
    <PackageVersion Include="HotChocolate.AspNetCore" Version="15.1.11" />
    <PackageVersion Include="HotChocolate.AspNetCore.Authorization" Version="15.1.11" />
    <PackageVersion Include="HotChocolate.Types" Version="15.1.11" />
    <PackageVersion Include="LinqKit.Core" Version="1.2.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.DataProtection" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Octokit" Version="14.0.0" />
    <PackageVersion Include="RestSharp" Version="112.1.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageVersion Include="Serilog.Expressions" Version="5.0.0" />
    <PackageVersion Include="StrawberryShake.Server" Version="15.1.11" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
</Project>