services:
  prdeploy-api:
    image: "${CONTAINER_REGISTRY:-greggbjensen/}prdeploy-api:${VERSION:-1.0.0-local}"
    build:
      context: .
      args:
        VERSION: "${VERSION:-1.0.0-local}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8087:80"
