version: '3.4'

services:
  prdeploy-api:
    image: "${CONTAINER_REGISTRY:-prdeploy.local/}prdeploy-api:${VERSION:-1.0.0-local}"
    build:
      context: ../
      dockerfile: prdeploy-api/src/PrDeploy.Api/Dockerfile
      args:
        VERSION: "${VERSION:-1.0.0-local}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8087:80"
