version: '3.8'

services:
  prdeploy-app:
    image: '${CONTAINER_REGISTRY:-greggbjensen.local/}prdeploy-app:${VERSION:-1.0.0-local}'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: '${VERSION:-1.0.0-local}'
    ports:
      - '3000:3000'
    environment:
      PRIVATE_KEY_PATH: '/app/gh_app_key.pem'
      DEFAULT_SETTINGS_FILE: '/app/settings/.default-prdeploy.yaml'
    volumes:
      - ./gh_app_key.pem:/app/gh_app_key.pem
      - ./.env:/app/.env
