<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" />
    <PackageReference Include="AWSSDK.SecurityToken" />
    <PackageReference Include="AWSSDK.SimpleSystemsManagement" />
    <PackageReference Include="AWSSDK.SSO" />
    <PackageReference Include="AWSSDK.SSOOIDC" />
    <PackageReference Include="LinqKit.Core" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Octokit" />
    <PackageReference Include="RestSharp" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PrDeploy.Api.Models\PrDeploy.Api.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Stores\Interfaces\" />
  </ItemGroup>

</Project>
