{{- $fullName := include "prdeploy.fullname" . -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "prdeploy.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.global.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "prdeploy.serviceAccounts.backend" . }}