{{- if .Values.global.serviceAccounts.frontend.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prdeploy.serviceAccounts.frontend" . }}
  labels:
    {{- include "prdeploy.labels" . | nindent 4 }}
  {{- with .Values.global.serviceAccounts.frontend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.global.serviceAccounts.frontend.automount }}
{{- end }}
