{{- if .Values.global.serviceAccounts.backend.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prdeploy.serviceAccounts.backend" . }}
  labels:
    {{- include "prdeploy.labels" . | nindent 4 }}
  {{- with .Values.global.serviceAccounts.backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.global.serviceAccounts.backend.automount }}
{{- end }}
