deployWorkflow: combined-deploy.yaml
environments:
  - name: dev
    queue: 'DEV_PR_QUEUE'
    color: '#d4ac0d'
    url: 'https://dev.myorg.com'
  - name: stage
    queue: 'STAGE_PR_QUEUE'
    color: '#2e86c1'
    url: 'https://stage.myorg.com'
    requireBranchUpToDate: true
  - name: prod
    queue: 'PROD_PR_QUEUE'
    color: '#1d8348'
    url: 'https://www.myorg.com'
    requireBranchUpToDate: true
    requireApproval: true
    excludeFromRollback: []
    automationTest:
      enabled: false
      workflow: test-automation-run.yaml
      inputs:
        environment: ${environment}
        pull_number: ${pull_number}
        run_name: ${run_name}
defaultEnvironment: dev
releaseEnvironment: prod
jira:
  addIssuesEnabled: false
settingsBranch: 'main'
builds:
  checkPattern: 'Build helm chart'
  workflowPattern: '/([^/]+?)-build.ya?ml'
slack:
  notificationsEnabled: false
badge:
  statusColors:
    error: '#ed6b6b'
    warn: '#edbe3e'
    success: '#29a329'
    info: '#52a9ff'
