apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "prdeploy-api.fullname" . }}-external
  labels:
    {{- include "prdeploy-api.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "prdeploy.fullname" . }}
    kind: SecretStore
  target:
    name: {{ include "prdeploy-api.fullname" . }}
    creationPolicy: Owner
  data:
    {{- range $key, $val := .Values.externalSecrets }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $val }}
    {{- end -}}