{{- $root := . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prdeploy-app.fullname" . }}
  labels:
    {{- include "prdeploy-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $path, $bytes := .Files.Glob "secrets/*" }}
  {{ base $path }}: {{ tpl ($root.Files.Get $path) $root | b64enc }}
  {{- end }}
