name: Date version
description: Gets a set of release tags for deployment of Docker images and helm charts, this included `latest` and multiple versions like `1.2.15`, `1.2`, and `1`.
inputs:
  repository:
    required: true
    description: The docker repository to generate tags for.
outputs:
  tags:
    value: ${{ steps.deploy_tags.outputs.tags }}
    description: The comma separated list of tags to use.

runs:
  using: "composite"
  steps:

  - name: Get deploy tags
    id: deploy_tags
    shell: bash
    env:
      REPOSITORY: ${{ inputs.repository }}
      RELEASE_TAG: ${{ (github.event_name == 'release' && github.event.release.tag_name) && github.event.release.tag_name || 'temp' }}
    run: |
      if [ "$RELEASE_TAG" == "temp" ]; then
        echo "tags=temp" >> $GITHUB_OUTPUT
        exit 0
      fi

      IFS='.' read -ra parts <<< "$RELEASE_TAG"
      patch="$REPOSITORY:$RELEASE_TAG"
      minor="$REPOSITORY:${parts[0]}.${parts[1]}"
      major="$REPOSITORY:${parts[0]}"
      latest="$REPOSITORY:latest"
      tags="$patch, $minor, $major, $latest"
      echo "tags=$tags" >> $GITHUB_OUTPUT