global:
  ingress:
    tls:
      enabled: true
  serviceAccounts:
    backend:
      annotations:
        eks.amazonaws.com/role-arn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/prdeploy-backend'

prdeploy-api:
  image:
    tag: 1.0.0-local

prdeploy-app:
  image:
    tag: 1.0.0-local

prdeploy-webhooks:
  image:
    tag: 1.0.0-local
