services:
  prdeploy-app:
    image: '${CONTAINER_REGISTRY:-greggbjensen/}prdeploy-app:${VERSION:-1.0.0-local}'
    build:
      context: .
      args:
        VERSION: '${VERSION:-1.0.0-local}'
    ports:
      - '8087:80'
