name: "[Subworkflow] Build Image"

on:
  workflow_call:
    inputs:
      service_name:
        description: Name of the service and root folder it comes from.
        required: true
        type: string
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      DOCKER_BUILDKIT: 1
      HELM_EXPERIMENTAL_OCI: 1
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.service_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'release' && github.event.action == 'created' }}
          tags: ${{ (github.event_name == 'release' && github.release.tag_name) && format('greggbjensen/{0}:latest, greggbjensen/{0}:{1}', inputs.service_name, github.release.tag_name) || format('greggbjensen/{0}:temp', inputs.service_name) }}
          file: ${{ inputs.service_name }}/Dockerfile
          context: ${{ inputs.service_name }}