name: "[subworkflow] container build"

on:
  workflow_call:
    inputs:
      service_name:
        description: Name of the service and root folder it comes from.
        required: true
        type: string
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      DOCKER_BUILDKIT: 1
      HELM_EXPERIMENTAL_OCI: 1
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions
            ${{ inputs.service_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy tags
        id: deploy_tags
        uses: ./.github/actions/deploy-tags
        with:
          repository: greggbjensen/${{ inputs.service_name }}

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'release' && github.event.action == 'created' }}
          tags: ${{ steps.deploy_tags.outputs.tags }}
          file: ${{ inputs.service_name }}/Dockerfile
          context: ${{ inputs.service_name }}

      - name: Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: greggbjensen/${{ inputs.service_name }}
          readme-filepath: ${{ inputs.service_name }}/README.md
