name: prdeploy-webhooks - Build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
    paths:
      - prdeploy-webhooks/**
      - .github/workflows/prdeploy-webhooks-build.yaml
  push:        # TODO: Remove after testing.
    branches:
      - docker-builds
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      DOCKER_BUILDKIT: 1
      HELM_EXPERIMENTAL_OCI: 1
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          sparse-checkout: prdeploy-webhooks

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'release' && github.event.action == 'created' }}
          tags: ${{ (github.event_name == 'release' && github.release.tag_name) && format('greggbjensen/prdeploy-webhooks:latest, greggbjensen/prdeploy-webhooks:{0}', github.release.tag_name) || 'greggbjensen/prdeploy-webhooks:temp' }}
          file: prdeploy-webhooks/Dockerfile
          context: .